@pbSchema(['name' => 'article_archive.blade'])
@php
 $categories=\App\Models\ArticleCategory::query()->with(['articles'=>fn($q)=>$q->active()->forLanguage($lang)->latest('published_at')])->forLanguage($lang)->active()->orderBy('sort_order')->get();
@endphp
<main class="academic-page" id="ve-page-root" data-ve-root><div class="container">
<section class="academic-hero-mini"><div class="academic-hero-mini-inner"><h1 data-inline-field="title">{{ $content['title']??'' }}</h1><p data-inline-field="intro">{{ $content['intro']??'' }}</p></div></section>
<section class="academic-icons-card"><h2>{{ $siteSettings['section_academic']??($content['title']??'') }}</h2><div class="academic-strip">@foreach($categories as $category)<a class="academic-icon-btn" href="#category-{{ $category->id }}">@if($category->image_path)<img src="{{ asset(ltrim($category->image_path,'/')) }}" alt="{{ $category->title }}">@else<i class="{{ $category->icon_class?:'fa-solid fa-book-medical' }}"></i>@endif<span data-entity="category" data-entity-id="{{ $category->id }}" data-entity-field="title">{{ $category->title }}</span></a>@endforeach</div></section>
<div class="academic-content-zone">@foreach($categories as $category)<section class="category-panel active" id="category-{{ $category->id }}"><div class="category-panel-head"><div class="category-panel-title"><span class="category-panel-icon"><i class="{{ $category->icon_class?:'fa-solid fa-book-medical' }}"></i></span><div><h3 data-entity="category" data-entity-id="{{ $category->id }}" data-entity-field="title">{{ $category->title }}</h3></div></div></div><div class="article-list">@foreach($category->articles->take(max(1,(int)($content['limit']??12))) as $article)<article><a class="article-card" href="{{ \App\Support\CleanUrl::to('article?slug='.urlencode($article->slug),$lang) }}"><span class="article-thumb">@if($article->cover_image)<img src="{{ asset(ltrim($article->cover_image,'/')) }}" alt="{{ $article->title }}">@else<i class="fa-regular fa-image"></i>@endif</span><span class="article-card-copy"><h4 data-entity="article" data-entity-id="{{ $article->id }}" data-entity-field="title">{{ $article->title }}</h4><p data-entity="article" data-entity-id="{{ $article->id }}" data-entity-field="excerpt">{{ \Illuminate\Support\Str::limit(strip_tags($article->excerpt?:$article->body),150) }}</p><span class="article-card-meta"><small>{{ optional($article->published_at?:$article->created_at)->format('d.m.Y') }}</small><span class="article-open">{{ $ui['read_more']??'' }} <i class="article-arrow fa-solid fa-arrow-right"></i></span></span></span></a></article>@endforeach</div></section>@endforeach</div>
</div></main>
