import React,{useEffect,useRef,useState}from'react';
const deep=v=>JSON.parse(JSON.stringify(v));
const makeId=t=>`${t}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
export default function Workspace({mount}){
 const base=mount.dataset.apiBase,key=mount.dataset.pageKey||'index',lang=mount.dataset.language||'az',csrf=document.querySelector('meta[name="csrf-token"]')?.content||'';
 const [data,setData]=useState(null),[doc,setDoc]=useState(null),[page,setPage]=useState(null),[draft,setDraft]=useState(null),[selected,setSelected]=useState(null),[zone,setZone]=useState('main'),[past,setPast]=useState([]),[future,setFuture]=useState([]),[modal,setModal]=useState(''),[note,setNote]=useState(''),[device,setDevice]=useState('desktop');const frame=useRef(null);
 const req=async(path,opts={})=>{const r=await fetch(base+path,{credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf,...opts.headers},...opts});const j=r.status===204?null:await r.json().catch(()=>({}));if(!r.ok)throw Error(j?.message||'Əməliyyat uğursuz oldu.');return j?.data};
 const load=async()=>{try{const x=await req(`/bootstrap?page_key=${encodeURIComponent(key)}&lang_code=${encodeURIComponent(lang)}`);setData(x.catalog);setDoc(x.document);setPage(x.page);setDraft(x.draft);setNote('') }catch(e){setNote(e.message)}};
 useEffect(()=>{load()},[]);
 const map=d=>zone==='main'?{sections:d.sections,order:d.order}:d.layout[zone];
 const apply=(fn)=>{const before=deep(doc),next=deep(doc);fn(next);setPast(p=>[...p.slice(-49),before]);setFuture([]);setDoc(next)};
 const undo=()=>{const x=past.at(-1);if(!x)return;setPast(p=>p.slice(0,-1));setFuture(p=>[...p,doc]);setDoc(x)};const redo=()=>{const x=future.at(-1);if(!x)return;setFuture(p=>p.slice(0,-1));setPast(p=>[...p,doc]);setDoc(x)};
 const add=t=>{const c=data.sections[t],id=makeId(t);apply(d=>{const m=zone==='main'?{sections:d.sections,order:d.order}:d.layout[zone];m.sections[id]={type:t,_name:null,disabled:false,slot_key:'default',settings:Object.fromEntries(Object.entries(c.fields).map(([k,v])=>[k,v.default??null])),blocks:{},order:[]};m.order.push(id);if(zone==='main'){d.sections=m.sections;d.order=m.order}else d.layout[zone]=m});setSelected(id);setModal('')};
 const pick=()=>{const m=map(doc);return selected?m.sections[selected]:null};
 const change=(field,value)=>apply(d=>{const m=zone==='main'?{sections:d.sections,order:d.order}:d.layout[zone];m.sections[selected].settings[field]=value;if(zone==='main'){d.sections=m.sections;d.order=m.order}else d.layout[zone]=m});
 const save=async(publish=false)=>{try{const r=await req('/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({page_key:page.page_key,document:doc,theme_settings:{},meta:page,expected_editor_revision:draft?.editor_revision||0})});setPage(r.page);setDraft(r.draft);setNote('Draft yadda saxlanıldı.');if(publish){const p=await req('/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({page_key:page.page_key,revision_id:r.draft.id})});setDraft(null);setNote(`Revision ${p.revision_number} dərc edildi.`)}}catch(e){setNote(e.message)}};
 const push=()=>{if(frame.current?.contentWindow&&doc&&data)frame.current.contentWindow.postMessage({channel:'altura-page-builder',type:'render',payload:{document:doc,catalog:data,selected,theme:{}}},location.origin)};
 useEffect(()=>{push()},[doc,data,selected]);useEffect(()=>{const l=e=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow||e.data?.channel!=='altura-page-builder')return;if(e.data.type==='ready')push();if(e.data.type==='select')setSelected(e.data.id)};addEventListener('message',l);return()=>removeEventListener('message',l)});
 if(!data||!doc||!page)return <div className="apb-loading">Page Builder yüklənir…</div>;
 const current=map(doc),node=pick(),schema=node?data.sections[node.type]:null,entries=Object.entries(data.sections).filter(([,v])=>!v.system&&(!v.zones?.length||v.zones.includes(zone)));
 return <div className="apb-shell"><header className="apb-topbar"><b className="apb-brand">AA Visual Builder</b><span>{note}</span><div className="apb-actions"><button onClick={undo} disabled={!past.length}>↶</button><button onClick={redo} disabled={!future.length}>↷</button><button onClick={()=>setModal('catalog')}>+ Section</button><button onClick={()=>save(false)}>Draft saxla</button><button className="publish" onClick={()=>save(true)}>Dərc et</button></div></header><main className="apb-workspace"><aside className="apb-panel"><div>{['main','header','footer'].map(z=><button key={z} className={zone===z?'active':''} onClick={()=>{setZone(z);setSelected(null)}}>{z}</button>)}</div>{current.order.map(id=><button className={'apb-tree '+(selected===id?'selected':'')} key={id} onClick={()=>setSelected(id)}>{current.sections[id].disabled?'○':'●'} {data.sections[current.sections[id].type]?.label||current.sections[id].type}</button>)}</aside><section className="apb-stage"><div><button onClick={()=>setDevice('desktop')}>Desktop</button><button onClick={()=>setDevice('tablet')}>Tablet</button><button onClick={()=>setDevice('mobile')}>Mobile</button></div><iframe ref={frame} className={device} title="Preview" sandbox="allow-scripts allow-same-origin" src={mount.dataset.canvasUrl} onLoad={push}/></section><aside className="apb-panel apb-inspector">{!node?<p>Section seçin.</p>:<><h3>{schema?.label}</h3><label>Gizlət<input type="checkbox" checked={node.disabled} onChange={e=>apply(d=>{const m=zone==='main'?{sections:d.sections,order:d.order}:d.layout[zone];m.sections[selected].disabled=e.target.checked;if(zone==='main')d.sections=m.sections;else d.layout[zone]=m})}/></label>{Object.entries(schema?.fields||{}).map(([k,f])=><label key={k}>{f.label}{f.type==='checkbox'?<input type="checkbox" checked={!!node.settings[k]} onChange={e=>change(k,e.target.checked)}/>:f.type==='select'?<select value={node.settings[k]??''} onChange={e=>change(k,e.target.value)}>{(f.options||[]).map(x=><option key={x}>{x}</option>)}</select>:['textarea','rich_text'].includes(f.type)?<textarea value={node.settings[k]??''} onChange={e=>change(k,e.target.value)}/>:<input type={f.type==='number'?'number':f.type==='color'?'color':'text'} value={node.settings[k]??''} onChange={e=>change(k,f.type==='number'?Number(e.target.value):e.target.value)}/>}</label>)}<button onClick={()=>{apply(d=>{const m=zone==='main'?{sections:d.sections,order:d.order}:d.layout[zone];delete m.sections[selected];m.order=m.order.filter(x=>x!==selected);if(zone==='main'){d.sections=m.sections;d.order=m.order}else d.layout[zone]=m});setSelected(null)}}>Sil</button></>}</aside></main>{modal==='catalog'&&<div className="apb-modal-backdrop"><div className="apb-modal"><button onClick={()=>setModal('')}>×</button><h3>Section əlavə et</h3>{entries.map(([k,v])=><button className="apb-catalog-item" key={k} onClick={()=>add(k)}>{v.label}<small>{v.category}</small></button>)}</div></div>}</div>}
