import React,{useEffect,useRef,useState}from'react';
const cp=v=>JSON.parse(JSON.stringify(v));const uid=t=>`${t}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
export default function Workspace({mount}){
 const base=mount.dataset.apiBase,key=mount.dataset.pageKey||'index',lang=mount.dataset.language||'az',token=document.querySelector('meta[name="csrf-token"]')?.content||'';
 const [data,setData]=useState(null),[doc,setDoc]=useState(null),[page,setPage]=useState(null),[draft,setDraft]=useState(null),[pages,setPages]=useState([]),[zone,setZone]=useState('main'),[root,setRoot]=useState(null),[child,setChild]=useState(null),[past,setPast]=useState([]),[future,setFuture]=useState([]),[modal,setModal]=useState(''),[note,setNote]=useState(''),[device,setDevice]=useState('desktop');const frame=useRef(null);
 const req=async(p,o={})=>{const r=await fetch(base+p,{credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':token,...o.headers},...o});const j=r.status===204?null:await r.json().catch(()=>({}));if(!r.ok)throw Error(j?.message||'Əməliyyat uğursuz oldu.');return j?.data};
 useEffect(()=>{Promise.all([req(`/bootstrap?page_key=${encodeURIComponent(key)}&lang_code=${encodeURIComponent(lang)}`),req(`/pages?lang_code=${encodeURIComponent(lang)}`)]).then(([x,p])=>{setData(x.catalog);setDoc(x.document);setPage(x.page);setDraft(x.draft);setPages(p||[])}).catch(e=>setNote(e.message))},[]);
 if(!data||!doc||!page)return <div className="apb-loading">Page Builder yüklənir…</div>;
 const getMap=d=>zone==='main'?{sections:d.sections,order:d.order}:d.layout[zone];
 const mutate=f=>{const before=cp(doc),next=cp(doc);f(next);setPast(v=>[...v.slice(-59),before]);setFuture([]);setDoc(next)};
 const undo=()=>{const x=past.at(-1);if(x){setPast(v=>v.slice(0,-1));setFuture(v=>[...v,doc]);setDoc(x)}};const redo=()=>{const x=future.at(-1);if(x){setFuture(v=>v.slice(0,-1));setPast(v=>[...v,doc]);setDoc(x)}};
 const map=getMap(doc),section=root?map.sections[root]:null,active=child&&section?section.blocks[child]:section,def=active?(child?(data.blocks[active.type]||data.sections[active.type]):data.sections[active.type]):null;
 const setField=(name,value)=>mutate(d=>{const m=getMap(d);const n=child?m.sections[root].blocks[child]:m.sections[root];n.settings[name]=value});
 const addSection=type=>{const c=data.sections[type],id=uid(type);mutate(d=>{const m=getMap(d);m.sections[id]={type,_name:null,disabled:false,slot_key:'default',settings:Object.fromEntries(Object.entries(c.fields).map(([k,v])=>[k,v.default??null])),blocks:{},order:[]};m.order.push(id)});setRoot(id);setChild(null);setModal('')};
 const addBlock=type=>{if(!section)return;const c=data.blocks[type]||data.sections[type],id=uid(type);mutate(d=>{const s=getMap(d).sections[root];s.blocks[id]={type,_name:null,disabled:false,slot_key:(def?.slots||['default'])[0],settings:Object.fromEntries(Object.entries(c.fields).map(([k,v])=>[k,v.default??null])),blocks:{},order:[]};s.order.push(id)});setChild(id);setModal('')};
 const remove=()=>{if(!root||!confirm('Seçilən komponent silinsin?'))return;mutate(d=>{const m=getMap(d);if(child){delete m.sections[root].blocks[child];m.sections[root].order=m.sections[root].order.filter(x=>x!==child)}else{delete m.sections[root];m.order=m.order.filter(x=>x!==root)}});if(child)setChild(null);else setRoot(null)};
 const duplicate=()=>{if(!root)return;const id=uid(active.type);mutate(d=>{const m=getMap(d);if(child){const s=m.sections[root];s.blocks[id]=cp(s.blocks[child]);s.order.splice(s.order.indexOf(child)+1,0,id)}else{m.sections[id]=cp(m.sections[root]);m.order.splice(m.order.indexOf(root)+1,0,id)}});child?setChild(id):setRoot(id)};
 const move=dir=>{if(!root)return;mutate(d=>{const m=getMap(d),order=child?m.sections[root].order:m.order,id=child||root,i=order.indexOf(id),j=dir==='up'?i-1:i+1;if(j>=0&&j<order.length)[order[i],order[j]]=[order[j],order[i]]})};
 const save=async(pub=false)=>{try{const r=await req('/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({page_key:page.page_key,document:doc,theme_settings:{},meta:page,expected_editor_revision:draft?.editor_revision||0})});setPage(r.page);setDraft(r.draft);frame.current?.contentWindow?.location.reload();if(pub){const p=await req('/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({page_key:page.page_key,revision_id:r.draft.id})});setDraft(null);frame.current?.contentWindow?.location.reload();setNote(`Revision ${p.revision_number} dərc edildi.`)}else setNote('Draft yadda saxlanıldı.')}catch(e){setNote(e.message)}};
 const entries=Object.entries(data.sections).filter(([,v])=>!v.system&&(!v.zones?.length||v.zones.includes(zone)));const blocks=section?((data.sections[section.type]?.blocks||[]).map(t=>[t,data.blocks[t]||data.sections[t]]).filter(([,v])=>v)):[];
 return <div className="apb-shell"><header className="apb-topbar"><b className="apb-brand">AA Visual Builder</b><select value={page.page_key} onChange={e=>location.assign(`${location.pathname}?page=${e.target.value}`)}>{pages.map(x=><option key={x.page_key} value={x.page_key}>{x.title}</option>)}</select><span>{note}</span><div className="apb-actions"><button onClick={undo} disabled={!past.length}>↶</button><button onClick={redo} disabled={!future.length}>↷</button><button onClick={()=>setModal('sections')}>+ Section</button><button onClick={()=>save(false)}>Draft</button><button className="publish" onClick={()=>save(true)}>Dərc et</button></div></header><main className="apb-workspace"><aside className="apb-panel"><div className="apb-zones">{['main','header','footer'].map(z=><button key={z} className={z===zone?'active':''} onClick={()=>{setZone(z);setRoot(null);setChild(null)}}>{z}</button>)}</div>{map.order.map(id=><div className="apb-tree-wrap" key={id}><button className={'apb-tree '+(id===root&&!child?'selected':'')} onClick={()=>{setRoot(id);setChild(null)}}>{map.sections[id].disabled?'○':'●'} {data.sections[map.sections[id].type]?.label||map.sections[id].type}</button>{id===root&&map.sections[id].order.map(c=><button className={'apb-tree apb-child '+(c===child?'selected':'')} key={c} onClick={()=>setChild(c)}>↳ {data.blocks[map.sections[id].blocks[c].type]?.label||map.sections[id].blocks[c].type}</button>)}</div>)}</aside><section className="apb-stage"><div><button onClick={()=>setDevice('desktop')}>Desktop</button><button onClick={()=>setDevice('tablet')}>Tablet</button><button onClick={()=>setDevice('mobile')}>Mobile</button><button onClick={()=>frame.current?.contentWindow?.location.reload()}>↻</button></div><iframe ref={frame} className={device} title="Preview" src={mount.dataset.canvasUrl}/></section><aside className="apb-panel apb-inspector">{!active?<p>Section və ya block seçin.</p>:<><h3>{def?.label||active.type}</h3><div><button onClick={()=>move('up')}>↑</button><button onClick={()=>move('down')}>↓</button><button onClick={duplicate}>Kopyala</button><button onClick={remove}>Sil</button></div><label>Gizlət<input type="checkbox" checked={active.disabled} onChange={e=>mutate(d=>{const m=getMap(d);const n=child?m.sections[root].blocks[child]:m.sections[root];n.disabled=e.target.checked})}/></label>{Object.entries(def?.fields||{}).map(([k,f])=><Field key={k} field={f} value={active.settings[k]} change={v=>setField(k,v)}/>) }{!child&&blocks.length>0&&<button className="primary" onClick={()=>setModal('blocks')}>+ İç blok</button>}</>}</aside></main>{modal==='sections'&&<Catalog title="Section əlavə et" rows={entries} choose={addSection} close={()=>setModal('')}/>} {modal==='blocks'&&<Catalog title="İç blok əlavə et" rows={blocks} choose={addBlock} close={()=>setModal('')}/>}</div>}
function Field({field,value,change}){if(field.type==='checkbox')return <label>{field.label}<input type="checkbox" checked={!!value} onChange={e=>change(e.target.checked)}/></label>;if(field.type==='select')return <label>{field.label}<select value={value??''} onChange={e=>change(e.target.value)}>{(field.options||[]).map(x=><option key={x}>{x}</option>)}</select></label>;return <label>{field.label}{['textarea','rich_text'].includes(field.type)?<textarea value={value??''} onChange={e=>change(e.target.value)}/>:<input type={field.type==='number'?'number':field.type==='color'?'color':'text'} value={value??''} onChange={e=>change(field.type==='number'?Number(e.target.value):e.target.value)}/>}</label>}
function Catalog({title,rows,choose,close}){return <div className="apb-modal-backdrop"><div className="apb-modal"><button onClick={close}>×</button><h3>{title}</h3>{rows.map(([id,v])=><button className="apb-catalog-item" key={id} onClick={()=>choose(id)}>{v.label}<small>{v.category}</small></button>)}</div></div>}
