<?php

namespace App\Support;

class PublicUiText
{
    public static function all(string $language): array
    {
        return match ($language) {
            'en' => self::en(),
            'ru' => self::ru(),
            'tr' => self::tr(),
            default => self::az(),
        };
    }

    private static function az(): array
    {
        return [
            'search' => 'Axtarış',
            'search_min_chars' => 'Axtarış üçün ən azı 3 simvol yazın.',
            'search_no_results' => 'Nəticə tapılmadı.',
            'searching' => 'Axtarılır...',
            'all_rights' => 'Bütün hüquqlar qorunur.',
            'privacy_policy' => 'Məxfilik siyasəti',
            'terms' => 'İstifadə şərtləri',
            'footer_contact' => 'Əlaqə',
            'view_all' => 'Hamısına bax',
            'courses_and_conferences' => 'Təlim və konfranslar',
            'gallery' => 'Qalereya',
            'gallery_intro' => 'Alturamedix Academy tədbirləri, təlimləri və akademik fəaliyyətlərindən görüntülər.',
            'gallery_empty' => 'Qalereyada hələ şəkil yoxdur.',
            'google_login' => 'Google ilə daxil ol',
            'google_register' => 'Google ilə qeydiyyat / giriş',
            'full_name' => 'Ad soyad',
            'phone' => 'Telefon',
            'address' => 'Ünvan',
            'subject' => 'Mövzu',
            'message' => 'Mesaj',
            'send' => 'Göndər',
            'send_message' => 'Mesaj göndər',
            'password_confirmation' => 'Şifrə təkrarı',
            'profile' => 'Profil',
            'registration_date' => 'Qeydiyyat tarixi',
            'email_notifications' => 'Email bildirişləri',
            'status' => 'Status',
            'active' => 'Aktiv',
            'inactive' => 'Passiv',
            'register' => 'Qeydiyyat',
            'register_now' => 'Qeydiyyatdan keç',
            'location_map' => 'Ünvan xəritəsi',
            'no_active_trainings' => 'Hazırda aktiv təlim yoxdur.',
            'no_articles' => 'Bu dildə hələ məqalə əlavə edilməyib.',
            'previous_slide' => 'Əvvəlki slayd',
            'next_slide' => 'Növbəti slayd',
            'slider_navigation' => 'Slider naviqasiyası',
            'slide' => 'slayd',
            'partners' => 'Tərəfdaşlarımız',
            'academic_hint' => 'Simgənin üzərinə klik edin, həmin bölmənin məqalələri aşağıda açılsın.',
            'categories_empty' => 'Hələ akademik kateqoriya əlavə edilməyib.',
            'articles_found' => 'məqalə tapıldı',
            'no_article_text' => 'Bu məqalə üçün mətn əlavə edilməyib.',
            'open_article_page' => 'Ayrı səhifədə aç',
            'category_empty' => 'Bu kateqoriyada hələ məqalə əlavə edilməyib.',
            'choose_academic_section' => 'Yuxarıdakı akademik bölmələrdən birini seçin.',
            'article_not_found' => 'Məqalə tapılmadı',
            'article_not_found_desc' => 'Seçilmiş məqalə mövcud deyil və ya passivdir.',
            'cert_valid' => 'Keçərlidir',
            'cert_expired' => 'Müddəti bitib',
            'cert_revoked' => 'Ləğv edilib',
            'cert_unknown' => 'Naməlum',
            'cert_check_title' => 'Sənəd yoxlanışı',
            'cert_check_desc' => 'Sənəd nömrəsini daxil edin.',
            'certificate_number' => 'Sənəd nömrəsi',
            'certificate_placeholder' => 'Məsələn: ALT-2026-XXXX',
            'verify' => 'Yoxla',
            'document' => 'Sənəd',
            'type' => 'Tip',
            'issue_date' => 'Verilmə tarixi',
            'expiry_date' => 'Bitmə tarixi',
            'lifetime' => 'Ömürlük',
            'revocation_reason' => 'Ləğv səbəbi',
            'note' => 'Qeyd',
            'view_document' => 'Sənədə bax',
            'certificate_not_found' => 'Bu nömrə ilə sertifikat və ya diplom tapılmadı. Nömrəni düzgün yazdığınıza əmin olun.',
        ];
    }

    private static function en(): array
    {
        return [
            'search' => 'Search',
            'search_min_chars' => 'Enter at least 3 characters to search.',
            'search_no_results' => 'No results found.',
            'searching' => 'Searching...',
            'all_rights' => 'All rights reserved.',
            'privacy_policy' => 'Privacy policy',
            'terms' => 'Terms of use',
            'footer_contact' => 'Contact',
            'view_all' => 'View all',
            'courses_and_conferences' => 'Courses and Conferences',
            'gallery' => 'Gallery',
            'gallery_intro' => 'Photos from Alturamedix Academy events, courses, and academic activities.',
            'gallery_empty' => 'No gallery images have been added yet.',
            'google_login' => 'Sign in with Google',
            'google_register' => 'Register / sign in with Google',
            'full_name' => 'Full name',
            'phone' => 'Phone',
            'address' => 'Address',
            'subject' => 'Subject',
            'message' => 'Message',
            'send' => 'Send',
            'send_message' => 'Send a message',
            'password_confirmation' => 'Confirm password',
            'profile' => 'Profile',
            'registration_date' => 'Registration date',
            'email_notifications' => 'Email notifications',
            'status' => 'Status',
            'active' => 'Active',
            'inactive' => 'Inactive',
            'register' => 'Register',
            'register_now' => 'Create account',
            'location_map' => 'Location map',
            'no_active_trainings' => 'There are no active courses at the moment.',
            'no_articles' => 'No articles have been added in this language yet.',
            'previous_slide' => 'Previous slide',
            'next_slide' => 'Next slide',
            'slider_navigation' => 'Slider navigation',
            'slide' => 'slide',
            'partners' => 'Our Partners',
            'academic_hint' => 'Click an icon to open articles from that section below.',
            'categories_empty' => 'No academic categories have been added yet.',
            'articles_found' => 'articles found',
            'no_article_text' => 'No text has been added for this article.',
            'open_article_page' => 'Open on separate page',
            'category_empty' => 'No articles have been added in this category yet.',
            'choose_academic_section' => 'Choose one of the academic sections above.',
            'article_not_found' => 'Article not found',
            'article_not_found_desc' => 'The selected article does not exist or is inactive.',
            'cert_valid' => 'Valid',
            'cert_expired' => 'Expired',
            'cert_revoked' => 'Revoked',
            'cert_unknown' => 'Unknown',
            'cert_check_title' => 'Document verification',
            'cert_check_desc' => 'Enter the document number.',
            'certificate_number' => 'Document number',
            'certificate_placeholder' => 'Example: ALT-2026-XXXX',
            'verify' => 'Verify',
            'document' => 'Document',
            'type' => 'Type',
            'issue_date' => 'Issue date',
            'expiry_date' => 'Expiry date',
            'lifetime' => 'Lifetime',
            'revocation_reason' => 'Revocation reason',
            'note' => 'Note',
            'view_document' => 'View document',
            'certificate_not_found' => 'No certificate or diploma was found with this number. Make sure the number is typed correctly.',
        ];
    }

    private static function tr(): array
    {
        return [
            'search' => 'Ara',
            'search_min_chars' => 'Arama için en az 3 karakter yazın.',
            'search_no_results' => 'Sonuç bulunamadı.',
            'searching' => 'Aranıyor...',
            'all_rights' => 'Tüm hakları saklıdır.',
            'privacy_policy' => 'Gizlilik politikası',
            'terms' => 'Kullanım şartları',
            'footer_contact' => 'İletişim',
            'view_all' => 'Tümünü görüntüle',
            'courses_and_conferences' => 'Kurslar ve Konferanslar',
            'gallery' => 'Galeri',
            'gallery_intro' => 'Alturamedix Academy etkinlikleri, kursları ve akademik faaliyetlerinden fotoğraflar.',
            'gallery_empty' => 'Galeriye henüz fotoğraf eklenmedi.',
            'google_login' => 'Google ile giriş yap',
            'google_register' => 'Google ile kayıt / giriş',
            'full_name' => 'Ad soyad',
            'phone' => 'Telefon',
            'address' => 'Adres',
            'subject' => 'Konu',
            'message' => 'Mesaj',
            'send' => 'Gönder',
            'send_message' => 'Mesaj gönder',
            'password_confirmation' => 'Şifre tekrarı',
            'profile' => 'Profil',
            'registration_date' => 'Kayıt tarihi',
            'email_notifications' => 'Email bildirimleri',
            'status' => 'Durum',
            'active' => 'Aktif',
            'inactive' => 'Pasif',
            'register' => 'Kayıt ol',
            'register_now' => 'Hesap oluştur',
            'location_map' => 'Adres haritası',
            'no_active_trainings' => 'Şu anda aktif kurs bulunmuyor.',
            'no_articles' => 'Bu dilde henüz makale eklenmedi.',
            'previous_slide' => 'Önceki slayt',
            'next_slide' => 'Sonraki slayt',
            'slider_navigation' => 'Slayt navigasyonu',
            'slide' => 'slayt',
            'partners' => 'Ortaklarımız',
            'academic_hint' => 'İlgili bölümün makalelerini aşağıda açmak için simgeye tıklayın.',
            'categories_empty' => 'Henüz akademik kategori eklenmedi.',
            'articles_found' => 'makale bulundu',
            'no_article_text' => 'Bu makale için metin eklenmedi.',
            'open_article_page' => 'Ayrı sayfada aç',
            'category_empty' => 'Bu kategoride henüz makale eklenmedi.',
            'choose_academic_section' => 'Yukarıdaki akademik bölümlerden birini seçin.',
            'article_not_found' => 'Makale bulunamadı',
            'article_not_found_desc' => 'Seçilen makale mevcut değil veya pasif durumdadır.',
            'cert_valid' => 'Geçerli',
            'cert_expired' => 'Süresi doldu',
            'cert_revoked' => 'İptal edildi',
            'cert_unknown' => 'Bilinmiyor',
            'cert_check_title' => 'Belge doğrulama',
            'cert_check_desc' => 'Belge numarasını girin.',
            'certificate_number' => 'Belge numarası',
            'certificate_placeholder' => 'Örnek: ALT-2026-XXXX',
            'verify' => 'Doğrula',
            'document' => 'Belge',
            'type' => 'Tip',
            'issue_date' => 'Veriliş tarihi',
            'expiry_date' => 'Bitiş tarihi',
            'lifetime' => 'Ömür boyu',
            'revocation_reason' => 'İptal nedeni',
            'note' => 'Not',
            'view_document' => 'Belgeyi görüntüle',
            'certificate_not_found' => 'Bu numara ile sertifika veya diploma bulunamadı. Numarayı doğru yazdığınızdan emin olun.',
        ];
    }

    private static function ru(): array
    {
        return [
            'search' => 'Поиск',
            'search_min_chars' => 'Введите минимум 3 символа для поиска.',
            'search_no_results' => 'Результаты не найдены.',
            'searching' => 'Идет поиск...',
            'all_rights' => 'Все права защищены.',
            'privacy_policy' => 'Политика конфиденциальности',
            'terms' => 'Условия использования',
            'footer_contact' => 'Контакты',
            'view_all' => 'Смотреть все',
            'courses_and_conferences' => 'Курсы и конференции',
            'gallery' => 'Галерея',
            'gallery_intro' => 'Фотографии с мероприятий, курсов и академической деятельности Alturamedix Academy.',
            'gallery_empty' => 'Фотографии в галерее пока не добавлены.',
            'google_login' => 'Войти через Google',
            'google_register' => 'Регистрация / вход через Google',
            'full_name' => 'Имя и фамилия',
            'phone' => 'Телефон',
            'address' => 'Адрес',
            'subject' => 'Тема',
            'message' => 'Сообщение',
            'send' => 'Отправить',
            'send_message' => 'Отправить сообщение',
            'password_confirmation' => 'Повторите пароль',
            'profile' => 'Профиль',
            'registration_date' => 'Дата регистрации',
            'email_notifications' => 'Email-уведомления',
            'status' => 'Статус',
            'active' => 'Активен',
            'inactive' => 'Неактивен',
            'register' => 'Регистрация',
            'register_now' => 'Зарегистрироваться',
            'location_map' => 'Карта адреса',
            'no_active_trainings' => 'Сейчас нет активных курсов.',
            'no_articles' => 'Для этого языка статьи пока не добавлены.',
            'previous_slide' => 'Предыдущий слайд',
            'next_slide' => 'Следующий слайд',
            'slider_navigation' => 'Навигация слайдера',
            'slide' => 'слайд',
            'partners' => 'Наши партнеры',
            'academic_hint' => 'Нажмите на иконку, чтобы открыть статьи выбранного раздела ниже.',
            'categories_empty' => 'Академические категории пока не добавлены.',
            'articles_found' => 'статей найдено',
            'no_article_text' => 'Текст для этой статьи пока не добавлен.',
            'open_article_page' => 'Открыть на отдельной странице',
            'category_empty' => 'В этой категории пока нет статей.',
            'choose_academic_section' => 'Выберите один из академических разделов выше.',
            'article_not_found' => 'Статья не найдена',
            'article_not_found_desc' => 'Выбранная статья не существует или неактивна.',
            'cert_valid' => 'Действителен',
            'cert_expired' => 'Срок истек',
            'cert_revoked' => 'Аннулирован',
            'cert_unknown' => 'Неизвестно',
            'cert_check_title' => 'Проверка документа',
            'cert_check_desc' => 'Введите номер документа.',
            'certificate_number' => 'Номер документа',
            'certificate_placeholder' => 'Например: ALT-2026-XXXX',
            'verify' => 'Проверить',
            'document' => 'Документ',
            'type' => 'Тип',
            'issue_date' => 'Дата выдачи',
            'expiry_date' => 'Дата окончания',
            'lifetime' => 'Бессрочно',
            'revocation_reason' => 'Причина аннулирования',
            'note' => 'Примечание',
            'view_document' => 'Посмотреть документ',
            'certificate_not_found' => 'Сертификат или диплом с этим номером не найден. Проверьте правильность номера.',
        ];
    }
}
